# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# Site settings
title: "Nem prensa"
description: > # this means to ignore newlines until "email:"
    Nesse diário de bordo queremos manter os aprendizados bem catalogados e sem
    informação ambigua, para isso iremos manter poucos posts, porêm todos serão
    atualizados sempre que se mostrarem equivocados.

    Queremos manter também todo o histórico de mudanças nos textos, para que
    seja possivel reve-los e entender a linha de raciocínio para cada decisão
    que tomamos no plantio.

email: nemprensa@gmail.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Nem Prensa'
author: 'NemPrensa'
author_image: "/assets/images/author.png"

paginate:	5

url: "https://nem-prensa.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: twitter user

#fill in disqus shortname to use disqus
disqus: nem-prensa

google_analytics: UA-113324249-1

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="
#
#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/nem-prensa/nem-prensa.github.io/
    desc:	GitHub Repository
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
